import streamlit as st
import requests

# ============================================================================
# PAGE CONFIG
# ============================================================================

st.set_page_config(
    page_title="Credit Card Fraud Detection",
    page_icon="💳",
    layout="centered"
)

API_URL = "http://localhost:8000/predict"

# ============================================================================
# TITLE
# ============================================================================

st.title("💳 Credit Card Fraud Detection")
st.write(
    "Enter the transaction details below. "
    "The prediction is generated by a FastAPI backend running a trained LightGBM model."
)

st.divider()

# ============================================================================
# INPUTS
# ============================================================================

amount = st.number_input(
    " Transaction Amount ($)",
    min_value=0.0,
    value=100.0,
    step=10.0,
    help="Actual transaction amount in dollars."
)

hour = st.slider(
    " Transaction Time (24-hour clock)",
    0,
    23,
    14,
    help="0 = Midnight, 12 = Noon, 23 = 11 PM"
)

late_night = st.selectbox(
    " Late Night Transaction (1 AM - 4 AM)?",
    ["No", "Yes"]
)

amount_type = st.selectbox(
    " Transaction Amount Pattern",
    [
        "Normal",
        "Slightly Unusual",
        "Very Unusual",
        "Extremely Unusual"
    ],
    help="How unusual is this transaction compared to the customer's normal spending?"
)

small_transaction = st.selectbox(
    "💳 Small Test Transaction (< $10)?",
    ["No", "Yes"],
    help="Fraudsters sometimes make very small purchases before larger ones."
)

# ============================================================================
# FEATURE ENGINEERING
# ============================================================================

import numpy as np

log_amount = np.log1p(amount)

mapping = {
    "Normal": 0.0,
    "Slightly Unusual": 1.0,
    "Very Unusual": 2.5,
    "Extremely Unusual": 4.0
}

amount_zscore = mapping[amount_type]

payload = {
    "log_amount": float(log_amount),
    "hour_of_day": float(hour),
    "is_night": 1 if late_night == "Yes" else 0,
    "amount_zscore": float(amount_zscore),
    "is_small_transaction": 1 if small_transaction == "Yes" else 0
}

# ============================================================================
# BUTTON
# ============================================================================

st.divider()

if st.button("🔍 Predict Fraud", use_container_width=True):

    with st.spinner("Contacting FastAPI..."):

        try:

            response = requests.post(API_URL, json=payload)

            if response.status_code == 200:

                result = response.json()

                probability = result["probability"] * 100
                decision = result["decision"]
                risk = result["risk_level"]

                st.success("Prediction Completed")

                st.metric(
                    "Fraud Probability",
                    f"{probability:.2f}%"
                )

                if decision == "APPROVE":
                    st.success("✅ APPROVE")
                elif decision == "REVIEW":
                    st.warning("🟡 REVIEW")
                else:
                    st.error("⛔ BLOCK")

                st.write("### Risk Level")

                if risk == "LOW":
                    st.success("LOW")
                elif risk == "MEDIUM":
                    st.warning("MEDIUM")
                else:
                    st.error("HIGH")

                st.write("### API Response")

                st.json(result)

            else:

                st.error(f"API Error ({response.status_code})")

                st.write(response.text)

        except Exception as e:

            st.error("Could not connect to FastAPI.")

            st.code(str(e))

# ============================================================================
# FOOTER
# ============================================================================

st.divider()

st.caption(
    "Backend: FastAPI | Model: LightGBM | Frontend: Streamlit | Containerized with Docker"
)
st.sidebar.title("About")

st.sidebar.info(
"""
This application uses

- LightGBM
- FastAPI
- Docker
- Streamlit

The Streamlit app sends requests to FastAPI, which loads the trained model and returns predictions.
"""
)